name: Frogbot Scan Pull Request (KriptoStream)

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    env:
      JF_URL: ${{ secrets.JF_URL }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      JF_GIT_TOKEN: ${{ secrets.JF_GIT_TOKEN }}
      JF_WATCHES: "krypto-data-dev-watch"
      JF_FAIL: "true"
    steps:
      - name: Frogbot Scan Pull Request
        uses: jfrog/frogbot@v2
